### ISSUE TITLE
多次访问不存在的URL时panic

### ISSUE THREAD

**Issue by ygmpkk** [AlexanderChen1989/xrest#1]
```
panic: net/http: CloseNotify called after ServeHTTP finished

goroutine 35 [running]:
panic(0x4780a0, 0xc82022a1b0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x3e6
net/http.(*response).CloseNotify(0xc82022c0d0, 0x0)
    /usr/local/opt/go/libexec/src/net/http/server.go:1535 +0x9d
github.com/AlexanderChen1989/xrest/plugs/close.(*closer).ServeHTTP.func1(0xd80628, 0xc82022c0d0, 0xc82022a100, 0xc8201ac980, 0xc820248000)
    /Users/timothy/workspace/idcos/idcos-puppet-config/vendor/src/github.com/AlexanderChen1989/xrest/plugs/close/close.go:36 +0x27
created by github.com/AlexanderChen1989/xrest/plugs/close.(*closer).ServeHTTP
    /Users/timothy/workspace/idcos/idcos-puppet-config/vendor/src/github.com/AlexanderChen1989/xrest/plugs/close/close.go:41 +0x124
```

**Comment by ygmpkk** [comment]
解决了，在注册Plug的时候，Close要在最后注册。

**Comment by AlexanderChen1989** [comment]
这个我需要改进一下文档

**Comment by ygmpkk** [comment]
建议改进插件体系，加入加载顺序和依赖关系
